//
//  IterableConstants.h
//  Iterable-iOS-SDK
//
//  Created by David Truong on 9/9/16.
//  Copyright © 2016 Iterable. All rights reserved.
//

#ifndef IterableConstants_h
#define IterableConstants_h

#define ITERABLE_IN_APP_TITLE @"ITERABLE_IN_APP_TITLE"
#define ITERABLE_IN_APP_BODY @"ITERABLE_IN_APP_BODY"
#define ITERABLE_IN_APP_IMAGE @"ITERABLE_IN_APP_IMAGE"
#define ITERABLE_IN_APP_BUTTON @"ITERABLE_IN_APP_BUTTON"
#define ITERABLE_IN_APP_ACTION @"ITERABLE_IN_APP_ACTION"
#define ITERABLE_IN_APP_IMAGE @"ITERABLE_IN_APP_IMAGE"

#define ITERABLE_IN_APP_TYPE @"ITERABLE_IN_APP_TYPE"
#define ITERABLE_IN_APP_TYPE_TOP @"TOP"
#define ITERABLE_IN_APP_TYPE_BOTTOM @"BOTTOM"
#define ITERABLE_IN_APP_TYPE_CENTER @"CENTER"
#define ITERABLE_IN_APP_TYPE_FULL @"FULL"

//TextBlock
#define ITERABLE_IN_APP_TEXT @"ITERABLE_IN_APP_TEXT"
#define ITERABLE_IN_APP_TEXT_FONT @"ITERABLE_IN_APP_TEXT_FONT"
#define ITERABLE_IN_APP_TEXT_COLOR @"ITERABLE_IN_APP_TEXT_COLOR"

#define ITERABLE_IN_APP_BACKGROUND_COLOR @"ITERABLE_IN_APP_BACKGROUND_COLOR"

#define ITERABLE_IN_APP_BUTTON_ACTION @"ITERABLE_IN_APP_BUTTON_ACTION"

#endif /* IterableConstants_h */
